### ISSUE TITLE
Uncaught (in promise) TypeError: axios is not a function

### ISSUE THREAD

**Issue by sdancer75** [circa10a/easy-soap-request#64]
In a brand new react project using your example, I get this error: **Uncaught (in promise) TypeError: Axios is not a function**

```
bundle.js:908 Uncaught (in promise) TypeError: axios is not a function
    at soapRequest (bundle.js:908:10)
    at makeRequest (bundle.js:61:15)
    at App (bundle.js:78:3)
    at renderWithHooks (bundle.js:20108:22)
    at mountIndeterminateComponent (bundle.js:23392:17)
    at beginWork (bundle.js:24688:20)
    at beginWork$1 (bundle.js:29647:18)
    at performUnitOfWork (bundle.js:28917:16)
    at workLoopSync (bundle.js:28840:9)
    at renderRootSync (bundle.js:28813:11)
```

**Comment by circa10a** [comment]
I tried to reproduce but am unable to. Here's what I did:

## local http server

```python
#!/usr/bin/env python3
from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_response(200, "ok")
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header("Access-Control-Allow-Headers", "*")
        SimpleHTTPRequestHandler.end_headers(self)
    def do_POST(self):
        self.end_headers()
        message = "Hello, World! Here is a POST response"
        self.wfile.write(bytes(message, "utf8"))

    def do_OPTIONS(self):
        self.end_headers()
        message = "Hello, World! Here is a OPTIONS response"
        self.wfile.write(bytes(message, "utf8"))

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=int(sys.argv[1]) if len(sys.argv) > 1 else 8000)
```

To run the server: `python server.py`

## browser code

```html
<html>
<script src="https://cdn.jsdelivr.net/npm/easy-soap-request/dist/easy-soap-request.js"></script>
<script>
    const url = 'http://localhost:8000/';
    const sampleHeaders = {
        'Content-Type': 'text/xml;charset=UTF-8',
        SOAPAction: 'https://my-soap-action/something',
    };
    const xml = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                 <soapenv:Header/>
                 <soapenv:Body>Some Data</soapenv:Body>
                 </soapenv:Envelope>`;
    async function makeRequest() {
        const { response } = await soapRequest({ url: url, headers: sampleHeaders, xml: xml, timeout: 1000 });
        const { headers, body, statusCode } = response;
        console.log(headers);
        console.log(body);
        console.log(statusCode);
        document.body.innerHTML = body;
    };
    makeRequest();
</script>
<body></body>
</html>
```

## Results

### Console

<img width="1433" alt="Screenshot 2024-03-30 at 1 34 48 PM" src="https://github.com/circa10a/easy-soap-request/assets/21261388/67ec86d5-c373-404d-9b58-390148c3bf10">

### Network

<img width="1440" alt="Screenshot 2024-03-30 at 1 36 24 PM" src="https://github.com/circa10a/easy-soap-request/assets/21261388/071fce38-bf6c-4c1d-b841-8d1d8809b065">

What does your code look like? How are you bundling?
